
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppBar from "@/components/AppBar";
import ReduxProvider from "@/redux/ReduxProvider";
import { AppThemeContext, AppThemeContextProvider } from "@/context/AppThemeContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* server componet allows client components, 
         so create seperate client Components intead of making it to client compnent */}
        <ReduxProvider>
           <AppThemeContextProvider>
              <div className="container">
                {/* header */}
                <AppBar/>
                <main>
                      {children} 
                </main>
              </div>
          </AppThemeContextProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
