import { Metadata } from "next";
import { Customer } from "../models/Customer";
import Link from "next/link";
import { Suspense } from "react";


export const metadata: Metadata = {
    title: "Awesome App: Cutomers",
    description: "Customers Page generated by next app!",
    keywords: ["global customers", "tech companies", "forune 500"]
}

export default async function CustomerListing() {
    await new Promise(resolve => setTimeout(resolve, 3000));
    return (
        <div>
            <h4>Customer Listing</h4>
            <Suspense fallback={<div className="alert alert-danger">Loading customers #1</div>} >
                <CustomersPage timeout={7000} />
            </Suspense>
            <Suspense fallback={<div className="alert alert-warning">Loading customers #2</div>} >
                <CustomersPage timeout={9000} />
            </Suspense>
        </div>
    )
}

export async function CustomersPage({ timeout }: { timeout: number }) {
    await new Promise(resolve => setTimeout(resolve, timeout));
    console.log("rendering customers...");
    //const url = "http://localhost:9000/customers"
    const url = `${process.env.BASE_URL}/customers`
    const response = await fetch(url, { method: "GET" });
    const customers = await response.json() as Customer[];
    return (
        <div className="container">
            <h5 id="customers">Customers</h5>
            <div>
                <table className="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Customer Id
                            </th>
                            <th>
                                Customer Name
                            </th>
                            <th>
                                Customer Location
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {customers.map((customer) => (
                            <tr key={customer.id}>
                                <td>{customer.id}</td>
                                <td><Link href={"/customers/" + customer.id}>{customer.name}</Link></td>
                                <td>{customer.location}</td>
                            </tr>
                        )
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    )
}