import { Metadata } from "next";
import { Customer } from "../models/Customer";


export const metadata:Metadata={
  title:"Cutomers",
  description:"Customers Page generated by next app!",
  keywords:["global customers", "tech companies","forune 500"]
}

export default async function CustomersPage() {

    //const url = "http://localhost:9000/customers"
    const url = `${process.env.BASE_URL}/customers`
    const response = await fetch(url, { method: "GET" });
    const customers = await response.json() as Customer[];
    return (
        <div className="container">
            <h5>Customers</h5>
            <div>
                <table className="table">
                    <tr>
                        <th>
                            Customer Id
                        </th>
                        <th>
                            Customer Name
                        </th>
                        <th>
                            Customer Location
                        </th>
                    </tr>
                    {customers.map((customer) => (
                        <tr key={customer.id}>
                            <td>{customer.id}</td>
                            <td>{customer.name}</td>
                            <td>{customer.location}</td>
                        </tr>
                    )
                    )}
                </table>
            </div>
        </div>
    )
}